CREATE TABLE TB_BOOK(
	BOOK_NO NUMBER CONSTRAINT TB_BOOK_PK PRIMARY KEY,
	BOOK_TITLE VARCHAR2(50) NOT NULL,
	BOOK_CONTENT VARCHAR2(4000) NOT NULL,
	BOOK_AUTHOR VARCHAR2(400) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE
);


COMMENT ON COLUMN TB_BOOK.BOOK_NO IS '번호';
COMMENT ON COLUMN TB_BOOK.BOOK_TITLE IS '책 제목';
COMMENT ON COLUMN TB_BOOK.BOOK_CONTENT IS '독서 기록';
COMMENT ON COLUMN TB_BOOK.BOOK_AUTHOR IS '작가';
COMMENT ON COLUMN TB_BOOK.REG_DATE IS '작성일';

CREATE SEQUENCE SEQ_BOOK_NO NOCACHE;

INSERT INTO TB_BOOK VALUES(SEQ_BOOK_NO.NEXTVAL, '물질의 세계', '모래.바람.물.', '에드 콘웨이', DEFAULT);

SELECT * FROM TB_BOOK;

COMMIT;

-- 독서 기록 목록 조회
SELECT BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, TO_CHAR(REG_DATE, 'YYYY-MM-DD') REG_DATE 
FROM TB_BOOK 
ORDER BY BOOK_NO;

-- 독서 기록 상세 조회
SELECT *
FROM TB_BOOK
WHERE BOOK_NO = ?;

-- 독서 기록 수정

-- 독서 기록 삭제
